package com.emerging.service.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class UserModel implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.name
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.age
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.type
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.create_date
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.name
	 * @return  the value of t_user.name
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.name
	 * @param name  the value for t_user.name
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.age
	 * @return  the value of t_user.age
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.age
	 * @param age  the value for t_user.age
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.type
	 * @return  the value of t_user.type
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.type
	 * @param type  the value for t_user.type
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.create_date
	 * @return  the value of t_user.create_date
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.create_date
	 * @param createDate  the value for t_user.create_date
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", age=").append(age);
		sb.append(", type=").append(type);
		sb.append(", createDate=").append(createDate);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}