package com.emerging.service.persistence.mapper;

import com.emerging.service.persistence.model.UserModel;
import com.emerging.service.persistence.model.UserModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	long countByExample(UserModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	int deleteByExample(UserModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	int insert(UserModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	int insertSelective(UserModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	List<UserModel> selectByExample(UserModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	UserModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	int updateByExampleSelective(@Param("record") UserModel record, @Param("example") UserModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	int updateByExample(@Param("record") UserModel record, @Param("example") UserModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	int updateByPrimaryKeySelective(UserModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Apr 19 11:28:41 CST 2019
	 */
	int updateByPrimaryKey(UserModel record);
}