spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  #    routes:
 #     - id: service-consumer
  #      uri: lb://SERVICE-CONSUMER
  #      predicates:
 #         - Path=/service-consumer/**
 #       filters:
 #         - StripPrefix=1 
